<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BANK BCA</name>
   <tag></tag>
   <elementGuidId>31a75cc6-c020-436d-b43f-140ca88f2fbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>root</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RegistrasiLoginProdukFAQEdukasi2Transaksi0Promo0Event0Sistem0Tips0Profil000Informasi PribadiInformasi BankTanda TanganKami menjaga dan melindungi informasi penting para pengguna Investasi Kita.Akun Bank RupiahBANK BCANama BankCabangNORMALVIRTUAL_ACCOUNTWALLETAccount TypeAFGHANISTANALBANIAALGERIAAMERICAN SAMOAANDORRAANGOLAANGUILLAANTIGUA AND BARBUDAARGENTINAARMENIAARUBAAUSTRALIAAUSTRIAAZERBAIJANBAHAMASBAHRAINBANGLADESHBARBADOSBELARUSBELGIUMBELIZEBENINBERMUDABHUTANBOLIVIABOSNIA AND HERZEGOVINABOTSWANABRAZILBRITISH INDIAN OCEAN TERRITORYBRUNEI DARUSSALAMBULGARIABURKINA FASOBURUNDICAMBODIACAMEROONCANADACAPE VERDECAYMAN ISLANDSCENTRAL AFRICAN REPUBLICCHADCHILECHINACHRISTMAS ISLANDSCOCOS (KEELING) ISLANDSCOLOMBIACOMOROSCONGOCOOK ISLANDSCOSTA RICACOTE D'IVOIRECROATIACUBACURACAOCYPRUSCZECH REPUBLICDEMOCRATIC REPUBLIC OF THE CONGDENMARKDJIBOUTIDOMINICADOMINICAN REPUBLICEAST TIMORECUADOREGYPTEL SALVADOREQUATORIAL GUINEAERITREAESTONIAETHIOPIAFALKLAND ISLANDS (MALVINAS)FAROE ISLANDFIJIFINLANDFORMER USSR(for ref)FRANCEFRENCH GUIANAFRENCH POLYNESIAGABONGAMBIAGEORGIAGERMANY, FED. REP. OFGHANAGIBRALTARGREECEGREENLANDGRENADAGUADELOUPEGUAMGUATEMALAGUINEAGUINEA BISSAUGUYANAHAITIHONDURASHONG KONGHUNGARYICELANDINDIAINDONESIAIRAN (ISLAMIC REPUBLIC OF)IRAQIRELANDISRAELITALYJAMAICAJAPANJORDANKAZAKHSTANKENYAKIRIBATIKOREA, DEMOCRATIC PEOPLE''S REPUBLICKOREA, REPUBLIC OFKUWAITKYRGYZSTANLAO PEOPLE'S DEMOCRATIC REPUBLICLATVIALEBANONLESOTHOLIBERIALIBYAN ARAB JAMAHIRIYALIECHTENSTEINLITHUANIALUXEMBOURGMACAUMADAGASCARMALAWIMALAYSIAMALDIVESMALIMALTAMARSHALL ISLANDSMARTINIQUEMAURITANIAMAURITIUSMEXICOMICRONESIA, FEDERATED STATE OFMOLDOVA, REPUBLIC OFMONACOMONGOLIAMONTENEGROMONTSERRATMOROCCOMOZAMBIQUEMYANMAR (FORM. BURMA)NAMIBIANAURUNEPALNETHERLANDSNETHERLANDS ANTILLESNEW CALEDONIANEW ZEALANDNICARAGUANIGERNIGERIANIUENORFOLK ISLANDSNORTHERN MARIANA ISLANDSNORWAYOMANOTH.C.&amp;S.AMERICAOTHER AFRICAOTHER EAST ASIAOTH NORTH AMERICAOTH.OCEANIAOTH.SOUTH &amp; S.E ASIAOTH.WEST ASIAOTH.WEST EUROPEPAKISTANPALAUPALESTINAPANAMAPAPUA NEW GUINEAPARAGUAYP. DEM.REP. OF YEMENPERUPHILIPPINESPOLANDPORTUGALPUERTO RICOQATARREP. OF MACEDONIAREUNIONROMANIARUSSIA FEDERATIONRWANDASAINT HELENASAINT KITTS AND NEVISSAINT LUCIASAINT VINCENT AND THE GRENADINESSAMOASAN MARINOSAO TOME AND PRINCIPESAUDI ARABIASENEGALSERBIASEYCHELLESSIERRA LEONESINGAPORESLOVAKIASLOVENIASOLOMON ISLANDSSOMALIASOUTH AFRICASOUTH GEORGIA AND THE SOUTH SASPAINSRI LANKASUDANSURINAMESWAZILANDSWEDENSWITZERLANDSYRIA ARAB REPUBLICTAIWANTAJIKISTANTANZANIA, UNITED REPUBLIC OFTHAILANDTIMOR LESTETOGOTOKELAUTONGATRINIDAD AND TOBAGOTUNISIATURKEYTURKMENISTANTURKS AND CAICOS ISLANDSTUVALUUGANDAUKRAINEUNITED ARAB EMIRATEUNITED KINGDOMUNITED STATESUNITED STATES MINOR OUTLYING ISLANDURUGUAYU.S. VIRGIN ISLANDSUZBEKISTANVANUATUVATICAN CITY STATE (HOLY SEE)VENEZUELAVIET NAMVIRGIN ISLANDS (BRITISH)WALLIS AND FUTUNA ISLANDSWESTERN SAHARAYEMENYUGOSLAVIAZAIREZAMBIAZIMBABWEBank CountryNomor RekeningIDRUSDCurrencyNama Pemilik RekeningSebelumnyaSelanjutnya</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='root']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Hallow, how are you. if you need our help don', &quot;'&quot;, 't hesitate to chat with us')])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='⚊'])[2]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div[3]</value>
   </webElementXpaths>
</WebElementEntity>
